version: "3.7"
services:
  api_todo:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todolist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL8.1.0
      
  db:
    image: "mysql:8.1.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: MySQL8.1.0
      MYSQL_DATABASE: todolist

networks:
  springapimysql-net: